# Generated by Django 3.0.3 on 2020-05-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='excel/%Y/%m/%d/'),
        ),
        migrations.AlterUniqueTogether(
            name='balancesheet',
            unique_together={('year', 'particular')},
        ),
    ]
