# Generated by Django 3.0.3 on 2020-05-31 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_auto_20200531_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.File'),
        ),
    ]
